spec:
  template:
    spec:
      containers:
      - name: twisterlab-api
        env:
        - name: ALLOWED_ORIGINS
          value: "http://localhost:3000,http://192.168.0.30:30091"
        - name: RATE_LIMIT_PER_MINUTE
          value: "60"
        volumeMounts:
        - name: source-code
          mountPath: /app/src/twisterlab
      volumes:
      - name: source-code
        hostPath:
          path: /c/Users/Administrator/Documents/twisterlab/src/twisterlab
          type: Directory
