apiVersion: v1
kind: Pod
metadata:
  name: builder
  namespace: twisterlab
spec:
  containers:
  - name: builder
    image: docker:cli
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    - name: transfer
      mountPath: /transfer
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: transfer
    hostPath:
      path: /tmp
